
//Auth Actions
//
export const	SIGNUP_REQUEST = "SIGNUP_REQUEST",
				SIGNUP_SUCCESS = "SIGNUP_SUCCESS",
				SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const	IS_LOGGED_IN = "IS_LOGGED_IN";

export const	LOGIN_REQUEST = "LOGIN_REQUEST",
				LOGIN_SUCCESS = "LOGIN_SUCCESS",
				LOGIN_FAILURE = "LOGIN_FAILURE",
				LOGOUT_REQUEST = "LOGOUT_REQUEST",
				LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
				LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const	LOAD_USER_REQUEST = "LOAD_USER_REQUEST",
				LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS",
				LOAD_USER_FAILURE = "LOAD_USER_FAILURE";
